### ISSUE TITLE
Sensors show status 'unknown'

### ISSUE THREAD

**Issue by grunzip** [macxq/foxess-ha#259]
Hello everyone and thank you for the integration.

For some time now, Foxess sensors do occasionally show the status 'unknown'. After some time (up to 1 hour) everything works fine again. During this time, I have no problems retrieving data via other channels (foxess app)
Since this behavior has not changed after the last update, I would like to report this here. Maybe someone has an idea what the problem is.

Thank you very much.

Greetings
Roland
![example](https://github.com/macxq/foxess-ha/assets/148907343/8f08d264-3dd2-42e9-8833-9bc808ea060d)

**From the Log-Files:**
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
Logger: custom_components.foxess.sensor
Quelle: custom_components/foxess/sensor.py:197
Integration: foxess (Dokumentation, Probleme)
Erstmals aufgetreten: 16:30:14 (5 Vorkommnisse)
Zuletzt protokolliert: 17:10:46

FoxESS has Cloud timeout or the Inverter is off-line, connection will be retried in 1 minute

**HA version:**
Core: 2024.6.3
Operating System: 12.3

**foxess-ha version:**
v0.41

**Hardware**
Raspberry Pi 3
rpi3-64

**Comment by FozzieUK** [comment]
Hi, thanks for reporting - it is actually a problem with the Fox ESS OpenAPI as it has been having performance problems at certain times of the day, usually from 12 noon to about 10pm with it going on / off-line throughout - the integration will try and re-connect at the earliest opportunity.

Fox are aware of it and know they need to make an investment in the infrastructure and resources and we are waiting for them to make that fix.

I'll leave this open for now so that others with the same problem can see why,  and will update if/when I hear anything further from Fox ESS about their expected time to fix this.

**Comment by timsdrew** [comment]
Thanks for this, have obviously noticed it as well. Do you have any ideas on how to get accurate daily (kwh) numbers out so that the energy dashboard is accurate?

**Comment by FozzieUK** [comment]
You should find the daily generated totals will be accurate as these are maintained in the cloud and so they should be more reliable than riemann sums on power values that might be missing because of timeouts.

.foxess_load
.foxess_feedin
.foxess_bat_charge
.foxess_bat_discharge
.foxess_grid_consumption
.foxess_energy_generated

and foxess_solar which is derived from those sensors using this calculation `energysolar = (loads + charge + feedIn - gridConsumption - discharge)`

On the latest version of the integration I keep these sensors available during cloud time outs, admittedly they will be the last known good total but the API usually responds well enough to keep them updated.

**Comment by grunzip** [comment]
> Hi, thanks for reporting - it is actually a problem with the Fox ESS OpenAPI as it has been having performance problems at certain times of the day, usually from 12 noon to about 10pm with it going on / off-line throughout - the integration will try and re-connect at the earliest opportunity.
> 
> Fox are aware of it and know they need to make an investment in the infrastructure and resources and we are waiting for them to make that fix.
> 
> I'll leave this open for now so that others with the same problem can see why, and will update if/when I hear anything further from Fox ESS about their expected time to fix this.

Thank you
