### ISSUE TITLE
sensor.foxess_grid_consumption - not showing corectly

### ISSUE THREAD

**Issue by benek984** [macxq/foxess-ha#31]
Hi,

In my Energy dashboard I use "sensor.foxess_grid_consumption" as electricity grid consumption.
When I look on the dashboard I see something strange. Between 2 and 4 o'clock at night I am charging my batteries using cheap tariff.  I can see this on the dashboard chart but grid consumption doesn't indicate this charging.
<img width="1440" alt="Screenshot 2022-01-22 at 19 55 55" src="https://user-images.githubusercontent.com/62546477/150653751-6a506a2d-2a19-4cf4-a8f2-4590ca0a64d3.png">

**Comment by macxq** [comment]
@benek984  how does it look like in https://www.foxesscloud.com/ ? can you validate that grid consumption data are same or different there?

**Comment by benek984** [comment]
Hi,

All data looks the same 


Cloud, HA sensors just Energy Dashboard shows incorrectly:

<img width="401" alt="Overview_-_Home_Assistant-2" src="https://user-images.githubusercontent.com/62546477/150696144-f9a51d1c-6302-4260-aea3-efcd2d744087.png">
<img width="398" alt="Screenshot 2022-01-23 at 20 05 45" src="https://user-images.githubusercontent.com/62546477/150696161-afa9b046-3f45-4b70-b136-f3abb9e7653d.png">


<img width="486" alt="Inverter_Details-6" src="https://user-images.githubusercontent.com/62546477/150696194-642d4664-723b-4b5c-8d8c-8fe524097669.png">

**Comment by Daibutt** [comment]
I think this may be a HA energy dashboard issue rather than foxess-HA. 
I use a 3rd party app for electricty import/export (NOT sensor.foxess_grid_consumption) and I get the same thing in the dashboard;

![image](https://user-images.githubusercontent.com/69276073/150930649-fc36c6b6-b786-4757-abf5-ce25509a02c2.png)

**Comment by williamjeccles** [comment]
Is this still an issue @Daibutt? I see in recent HA updates fixes for a number of energy bugs.

**Comment by Daibutt** [comment]
@williamjeccles I'm not sure as I don't have battery charge data with the HA foxess add-on disabled. I am guessing it still displays the data in that way. 
Either way it's not an issue for me, I was just commenting that it's not HA foxess specific.
It's a "feature" of the energy dashboard, it does the same with solar usage and battery charge from solar. I guess it's by design and shows in each hour where energy went.
